applepay - oncancel
paypal/paypal-checkout-components pull request #1984
Opened 2022-08-05 03:02 UTC by andyfen

changes
https://github.com/paypal/paypal-smart-payment-buttons/pull/452

2022-08-05 16:06 UTC, wsbrunson approved these changes

2022-08-06 12:48 UTC, mnicpt requested changes
@andyfen Let's get together and talk through this and issue 2.

2022-08-06 12:48 UTC, mnicpt commented on src/zoid/buttons/util.js
> -                oncancel: () => session.oncancel()
@andyfen Why are we refactoring this?  I think the issue is that when I look at SPB, the `oncancel` callback isn't being brought in from the response: https://github.com/paypal/paypal-smart-payment-buttons/blob/c12f7f31540246d593e53e3bbd4e68d29218817b/src/payment-flows/applepay/applepay.js#L345

2022-08-06 12:54 UTC, mnicpt commented on src/zoid/buttons/util.js
> -                oncancel: () => session.oncancel()
I see what happened.  This wasn't here before and was added.  Interesting this doesn't work though.  This should be fine.  Did we update the Apple Pay version.  I don't recall `abort` being supported last year.

2022-08-06 12:54 UTC, mnicpt approved these changes

2022-08-08 21:03 UTC, merged